### ISSUE TITLE
Should probably include a warning

### ISSUE THREAD

**Issue by afang** [719Ben/notice-me#3]
People who try this out without reading what it does might get their account banned for abuse.

**Comment by afang** [comment]
@Garbee sometimes I multi-task by cloning the repo and following the install instructions first. A bolded warning at the top would help a lot.

**Comment by jeroenvisser101** [comment]
![](https://www.dropbox.com/s/cyeuskvirqnpku3/Screenshot%202016-03-29%2021.00.39.png?dl=1)
